import Head from 'next/head'
import Image from 'next/image'
import Sidebar from './components/Sidebar'
import Feed from './components/Feed'
import { GetServerSidePropsContext } from 'next/types'
import {   ClientSafeProvider, getProviders,getSession,LiteralUnion,useSession } from 'next-auth/react'
import Login from './components/Login'
import { BuiltInProviderType } from 'next-auth/providers'





export default function Home(providers :Record<LiteralUnion<BuiltInProviderType, string>, ClientSafeProvider>) {

  const {data: session} = useSession();

  if(!session) return <Login providers={providers}/>

  return (
    <>
      <Head>
        <title>OpenHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico "  />
      </Head>
      
      <main className='bg-black min-h-screen flex max-w-[1500px] mx-auto'>
        {/*Sidebar*/}
        <Sidebar />

        {/*Feed*/}
        <Feed/>

        {/*Widgets*/}

        {/*Modal*/}

      </main>
      
      
    </>
  )
}

export async function getServerSideProps(context:GetServerSidePropsContext) {

  
  const providers = await getProviders();
  const session = await getSession(context)
  
  return {
    props: {
      providers,
      session
    }, 
  }
}